name: Verify backend

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Clone repo
      - name: Clone repository
        uses: actions/checkout@v2
      # Cache node modules
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-deps-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-deps-${{ hashFiles('yarn.lock') }}
      # Install dependencies and build backend
      - name: Build backend
        run: yarn && yarn build
        working-directory: "backend"
