name: Verify frontend

on:
  pull_request:
    branches:
      - prodiction

jobs:
  verify-frontend:
    name: "Verify frontend"
    runs-on: macos-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: "Terraform Initialization"
        uses: hashicorp/terraform-github-actions@master
        scripts:
          - cd ../../../frontend
          - yarn ci --no-progress
          - yarn build
          - yarn test
        with:
          tf_actions_version: 1.0.8
          tf_actions_subcommand: "init"
          tf_actions_cli_credentials_token: ${{ secrets.TF_API_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
